package Canada;

import JavaAPI.*;

public class TestCanadaPreauth
{
	public static void main(String[] args)
	{
		String store_id = "monca03650";
		String api_token = "7Yw0MPTlhjBRcZiE6837";
		java.util.Date createDate = new java.util.Date(); 
		String order_id = "Test"+createDate.getTime();
		String amount = "4840.00";
		String pan = "5454545454545454";
		String expdate = "2212"; //YYMM
		String crypt = "7";
		String processing_country_code = "CA";
		boolean status_check = false;

		PreAuth preauth = new PreAuth();
		preauth.setOrderId(order_id);
		preauth.setAmount(amount);
		preauth.setPan(pan);
		preauth.setExpdate(expdate);
		preauth.setCryptType(crypt);
		//preauth.setWalletIndicator(""); //Refer documentation for possible values
		//preauth.setCmId("8nAK8712sGaAkls56"); //set only for usage with Offlinx - Unique max 50 alphanumeric characters transaction id generated by merchant

		// TrId and TokenCryptogram are optional, refer documentation for more details.
		preauth.setTrId("50189815682");
		preauth.setTokenCryptogram("APmbM/411e0uAAH+s6xMAAADFA==");

		//optional - Installment Info
		InstallmentInfo installmentInfo = new InstallmentInfo();
		installmentInfo.setPlanId("ae859ef1-eb91-b708-8b80-1dd481746401");
		installmentInfo.setPlanIdRef("0000000065");
		installmentInfo.setTacVersion("2");
		//preauth.setInstallmentInfo(installmentInfo);

		//optional - Credential on File details
		CofInfo cof = new CofInfo();
		cof.setPaymentIndicator("C");
		cof.setPaymentInformation("0");
		//cof.setIssuerId("139X3130ASCXAS9"); 
		
		preauth.setCofInfo(cof);

		HttpsPostRequest mpgReq = new HttpsPostRequest();
		mpgReq.setProcCountryCode(processing_country_code);
		mpgReq.setTestMode(true); //false or comment out this line for production transactions
		mpgReq.setStoreId(store_id);
		mpgReq.setApiToken(api_token);
		mpgReq.setTransaction(preauth);
		mpgReq.setStatusCheck(status_check);
		mpgReq.send();

		try
		{
			Receipt receipt = mpgReq.getReceipt();

			System.out.println("CardType = " + receipt.getCardType());
			System.out.println("TransAmount = " + receipt.getTransAmount());
			System.out.println("TxnNumber = " + receipt.getTxnNumber());
			System.out.println("ReceiptId = " + receipt.getReceiptId());
			System.out.println("TransType = " + receipt.getTransType());
			System.out.println("ReferenceNum = " + receipt.getReferenceNum());
			System.out.println("ResponseCode = " + receipt.getResponseCode());
			System.out.println("ISO = " + receipt.getISO());
			System.out.println("BankTotals = " + receipt.getBankTotals());
			System.out.println("Message = " + receipt.getMessage());
			System.out.println("AuthCode = " + receipt.getAuthCode());
			System.out.println("Complete = " + receipt.getComplete());
			System.out.println("TransDate = " + receipt.getTransDate());
			System.out.println("TransTime = " + receipt.getTransTime());
			System.out.println("Ticket = " + receipt.getTicket());
			System.out.println("TimedOut = " + receipt.getTimedOut());
			System.out.println("IsVisaDebit = " + receipt.getIsVisaDebit());
			//System.out.println("StatusCode = " + receipt.getStatusCode());
			//System.out.println("StatusMessage = " + receipt.getStatusMessage());
			System.out.println("IssuerId = " + receipt.getIssuerId());
			System.out.println("SourcePanLast4 = " + receipt.getSourcePanLast4());
			System.out.println("Advice Code= "+ receipt.getAdviceCode());

			// InstallmentResults installmentResults = receipt.getInstallmentResults();

			// System.out.println("\nPlanId = " + installmentResults.getPlanId() +"\n");
			// System.out.println("PlanIDRef = " + installmentResults.getPlanIDRef());
			// System.out.println("TacVersion = " + installmentResults.getTacVersion());
			// System.out.println("PlanAcceptanceId = " + installmentResults.getPlanAcceptanceId());
			// System.out.println("PlanStatus = " + installmentResults.getPlanStatus()); 
			// System.out.println("PlanResponse = " + installmentResults.getPlanResponse());

		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
}
