package Canada;

import JavaAPI.*;

public class TestCanadaCavvPurchase
{
	public static void main(String[] args)
	{
		String store_id = "store5";
		String api_token = "yesguy";
		java.util.Date createDate = new java.util.Date();
		String order_id = "Test"+createDate.getTime();
		String cust_id = "CUS887H67";
		String amount = "10.42";
		String pan = "5204240750750692";
		String expdate = "2301"; //YYMM
		String cavv = "BwABApFSYyd4l2eQQFJjAAAAAAA=";
		String dynamic_descriptor = "123456";
		String processing_country_code = "CA";
		String crypt_type = "5";
		String ds_trans_id = "12345";
		boolean status_check = false;

		CavvPurchase cavvPurchase = new CavvPurchase();
		cavvPurchase.setOrderId(order_id);
		cavvPurchase.setCustId(cust_id);
		cavvPurchase.setAmount(amount);
		cavvPurchase.setPan(pan);
		cavvPurchase.setExpdate(expdate);
		cavvPurchase.setCavv(cavv);
		cavvPurchase.setCryptType(crypt_type); //Mandatory for AMEX only
		cavvPurchase.setDynamicDescriptor(dynamic_descriptor);
		//cavvPurchase.setWalletIndicator("APP"); //set only for wallet transactions. e.g APPLE PAY
		//cavvPurchase.setNetwork("Interac"); //set only for Interac e-commerce
		//cavvPurchase.setDataType("3DSecure"); //set only for Interac e-commerce
		//cavvPurchase.setCmId("8nAK8712sGaAkls56"); //set only for usage with Offlinx - Unique max 50 alphanumeric characters transaction id generated by merchant
		
		cavvPurchase.setThreeDSVersion("2"); //Mandatory for 3DS Version 2.0+
		cavvPurchase.setThreeDSServerTransId("e11d4985-8d25-40ed-99d6-c3803fe5e68f"); //Mandatory for 3DS Version 2.0+ - obtained from MpiCavvLookup or MpiThreeDSAuthentication 
		cavvPurchase.setDsTransId(ds_trans_id);//Optional - to be used only if you are using 3rd party 3ds 2.0 service

		// TrId and TokenCryptogram are optional, refer documentation for more details.
		cavvPurchase.setTrId("50189815682");
		cavvPurchase.setTokenCryptogram("APmbM/411e0uAAH+s6xMAAADFA==");

		//optional - Credential on File details
		CofInfo cof = new CofInfo();
		cof.setPaymentIndicator("U");
		cof.setPaymentInformation("2");
		cof.setIssuerId("139X3130ASCXAS9"); 
		
		cavvPurchase.setCofInfo(cof);

		HttpsPostRequest mpgReq = new HttpsPostRequest(); 
		mpgReq.setProcCountryCode(processing_country_code);
		mpgReq.setTestMode(true); //false or comment out this line for production transactions
		mpgReq.setStoreId(store_id);
		mpgReq.setApiToken(api_token);
		mpgReq.setTransaction(cavvPurchase);
		mpgReq.setStatusCheck(status_check);
		mpgReq.send();

		try
		{
			Receipt receipt = mpgReq.getReceipt();

			System.out.println("CardType = " + receipt.getCardType());
			System.out.println("TransAmount = " + receipt.getTransAmount());
			System.out.println("TxnNumber = " + receipt.getTxnNumber());
			System.out.println("ReceiptId = " + receipt.getReceiptId());
			System.out.println("TransType = " + receipt.getTransType());
			System.out.println("ReferenceNum = " + receipt.getReferenceNum());
			System.out.println("ResponseCode = " + receipt.getResponseCode());
			System.out.println("ISO = " + receipt.getISO());
			System.out.println("BankTotals = " + receipt.getBankTotals());
			System.out.println("Message = " + receipt.getMessage());
			System.out.println("AuthCode = " + receipt.getAuthCode());
			System.out.println("Complete = " + receipt.getComplete());
			System.out.println("TransDate = " + receipt.getTransDate());
			System.out.println("TransTime = " + receipt.getTransTime());
			System.out.println("Ticket = " + receipt.getTicket());
			System.out.println("TimedOut = " + receipt.getTimedOut());
			System.out.println("CavvResultCode = " + receipt.getCavvResultCode());
			System.out.println("IssuerId = " + receipt.getIssuerId());
			System.out.println("ThreeDSVersion = " + receipt.getThreeDSVersion());
			System.out.println("SourcePanLast4 = " + receipt.getSourcePanLast4());
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
}
